
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2W48HSG2p3CvMfeahwr7rfuESf50eb6I',
    appId: '1:857857815019:web:60dfb51d78dbfc15c8a9ae',
    messagingSenderId: '857857815019',
    projectId: 'second-e734b',
    authDomain: 'second-e734b.firebaseapp.com',
    storageBucket: 'second-e734b.firebasestorage.app',
    measurementId: 'G-48FD1B4R3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG_Qq86JKYoOHg3W86iy_B7_TUJy0Ucyk',
    appId: '1:857857815019:android:64e7f34cf38390d5c8a9ae',
    messagingSenderId: '857857815019',
    projectId: 'second-e734b',
    storageBucket: 'second-e734b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUP__vfJ5D-ML0F0gIcWLel8RMM-oVAA',
    appId: '1:857857815019:ios:bec03856fc220fa1c8a9ae',
    messagingSenderId: '857857815019',
    projectId: 'second-e734b',
    storageBucket: 'second-e734b.firebasestorage.app',
    iosBundleId: 'com.example.second',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtUP__vfJ5D-ML0F0gIcWLel8RMM-oVAA',
    appId: '1:857857815019:ios:bec03856fc220fa1c8a9ae',
    messagingSenderId: '857857815019',
    projectId: 'second-e734b',
    storageBucket: 'second-e734b.firebasestorage.app',
    iosBundleId: 'com.example.second',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2W48HSG2p3CvMfeahwr7rfuESf50eb6I',
    appId: '1:857857815019:web:20546cd41ccfe35ec8a9ae',
    messagingSenderId: '857857815019',
    projectId: 'second-e734b',
    authDomain: 'second-e734b.firebaseapp.com',
    storageBucket: 'second-e734b.firebasestorage.app',
    measurementId: 'G-838WJD4Q9K',
  );

}